apps/inkfish_web/lib/inkfish_web/router.ex
defmodule InkfishWeb.Router do
  use InkfishWeb, :router
  
  alias InkfishWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug Plugs.Assign, client_mode: :browser
    plug :fetch_session
    plug Plugs.FetchUser
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.Breadcrumb, {"Home", :page, :index}
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug Plugs.Assign, client_mode: :ajax
    plug :fetch_session
    plug Plugs.FetchUser
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end
  
  pipeline :admin do
    plug Plugs.RequireUser, is_admin: true
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", InkfishWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/dashboard", PageController, :dashboard
    resources "/session", SessionController, only: [:create, :delete], singleton: true
    resources "/users", UserController, only: [:show, :edit, :update]
    resources "/uploads", UploadController, only: [:create, :show]
    get "/uploads/:id/thumb", UploadController, :thumb
    resources "/courses", CourseController, only: [:index, :show] do
      resources "/regs", RegController, only: [:index, :new, :create]
      resources "/join_reqs", JoinReqController, only: [:new, :create]
      resources "/teams", TeamController, only: [:index, :new, :create]
    end
    resources "/regs", RegController, except: [:index, :new, :create]
    resources "/teams", TeamController, except: [:index, :new, :create]
    resources "/assignments", AssignmentController, only: [:show] do
      resources "/subs", SubController, only: [:new, :create]
    end
    resources "/subs", SubController, only: [:show]
    resources "/grade_columns", GradeColumnController, only: [:show]
    resources "/grades", GradeController, only: [:show]
  end

  scope "/staff", InkfishWeb.Staff, as: :staff do
    pipe_through :browser

    resources "/courses", CourseController do
      resources "/regs", RegController, only: [:index, :new, :create]
      resources "/join_reqs", JoinReqController, only: [:index]
      resources "/teamsets", TeamsetController, only: [:index, :new, :create]
      resources "/buckets", BucketController, only: [:index, :new, :create]
    end
    resources "/regs", RegController, except: [:index, :new, :create]
    resources "/join_reqs", JoinReqController, only: [:show, :delete]
    post "/join_reqs/:id/accept", JoinReqController, :accept
    resources "/teamsets", TeamsetController, except: [:index, :new, :create]
    resources "/buckets", BucketController, except: [:index, :new, :create] do
      resources "/assignments", AssignmentController, only: [:index, :new, :create]
    end
    resources "/assignments", AssignmentController, except: [:index, :new, :create] do
      resources "/grade_columns", GradeColumnController, only: [:index, :new, :create]
    end
    resources "/grade_columns", GradeColumnController, except: [:index, :new, :create]
    resources "/subs", SubController, only: [:show, :update] do
      resources "/grades", GradeController, only: [:create]
    end
    resources "/grades", GradeController, only: [:edit, :show]
  end

  scope "/admin", InkfishWeb.Admin, as: :admin do
    pipe_through [:browser, :admin]
    
    resources "/users", UserController
    resources "/courses", CourseController
    resources "/uploads", UploadController
  end

  scope "/ajax", InkfishWeb, as: :ajax do
    pipe_through :ajax

    post "/uploads", UploadController, :create
  end

  scope "/ajax/staff", InkfishWeb.Staff, as: :ajax_staff do
    pipe_through :ajax

    resources "/subs", SubController, only: [] do
      resources "/grades", GradeController, only: [:create]
    end
    resources "/grades", GradeController, only: [] do
      resources "/line_comments", LineCommentController, only: [:create]
    end
    resources "/line_comments", LineCommentController, except: [:new, :edit, :create]
    resources "/teamsets", TeamsetController, only: [] do
      resources "/teams", TeamController, only: [:index, :create]
    end
    resources "/teams", TeamController, only: [:show, :update, :delete]
  end
end

apps/inkfish_web/lib/inkfish_web/controllers/reg_controller.ex
defmodule InkfishWeb.RegController do
  use InkfishWeb, :controller

  alias Inkfish.Users
  alias Inkfish.Users.Reg

  plug InkfishWeb.Plugs.FetchItem, [course: "course_id"]
    when action in [:index, :new, :create]
  plug InkfishWeb.Plugs.FetchItem, [reg: "id"]
    when action not in [:index, :new, :create]

  def index(conn, %{"course_id" => course_id}) do
    regs = Users.list_regs_for_course(course_id)
    render(conn, "index.html", course_id: course_id, regs: regs)
  end

  def new(conn, %{"course_id" => course_id}) do
    changeset = Users.change_reg(%Reg{course_id: course_id})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"course_id" => course_id, "reg" => reg_params}) do
    reg_params = Map.put(reg_params, "course_id", course_id)
    case Users.create_reg(reg_params) do
      {:ok, reg} ->
        conn
        |> put_flash(:info, "Reg created successfully.")
        |> redirect(to: Routes.reg_path(conn, :show, reg))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    reg = Users.get_reg!(id)
    render(conn, "show.html", reg: reg)
  end

  def edit(conn, %{"id" => id}) do
    reg = Users.get_reg!(id)
    changeset = Users.change_reg(reg)
    render(conn, "edit.html", reg: reg, changeset: changeset)
  end

  def update(conn, %{"id" => id, "reg" => reg_params}) do
    reg = Users.get_reg!(id)

    case Users.update_reg(reg, reg_params) do
      {:ok, reg} ->
        conn
        |> put_flash(:info, "Reg updated successfully.")
        |> redirect(to: Routes.reg_path(conn, :show, reg))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", reg: reg, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    reg = Users.get_reg!(id)
    {:ok, _reg} = Users.delete_reg(reg) 

    conn
    |> put_flash(:info, "Reg deleted successfully.")
    |> redirect(to: Routes.course_reg_path(conn, :index, reg.course_id))
  end
end

apps/inkfish_web/lib/inkfish_web/controllers/staff/assignment_controller.ex
defmodule InkfishWeb.Staff.AssignmentController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs

  plug Plugs.FetchItem, [bucket: "bucket_id"]
    when action in [:index, :new, :create]
  plug Plugs.FetchItem, [assignment: "id"]
    when action not in [:index, :new, :create]

  plug Plugs.RequireReg, staff: true

  alias Plugs.Breadcrumb
  plug Breadcrumb, {"Courses (Staff)", :staff_course, :index}
  plug Breadcrumb, {:show, :staff, :course}
  plug Breadcrumb, {:show, :staff, :assignment}
    when action not in [:index, :new, :create, :show]

  alias Inkfish.Assignments
  alias Inkfish.Assignments.Assignment

  def index(conn, _params) do
    assignments = Assignments.list_assignments()
    render(conn, "index.html", assignments: assignments)
  end

  def new(conn, params) do
    teamsets = Inkfish.Teams.list_teamsets(conn.assigns[:course])
    today = Inkfish.LocalTime.today()
    {:ok, due} = NaiveDateTime.new(Date.add(today, 7), ~T[23:59:59])
    as = %Assignment{
      bucket_id: params["bucket_id"],
      teamset_id: hd(teamsets).id,
      weight: Decimal.new("1.0"),
      due: due,
    }
    changeset = Assignments.change_assignment(as)
    render(conn, "new.html", changeset: changeset, teamsets: teamsets)
  end

  def create(conn, %{"assignment" => assignment_params}) do
    case Assignments.create_assignment(assignment_params) do
      {:ok, assignment} ->
        conn
        |> put_flash(:info, "Assignment created successfully.")
        |> redirect(to: Routes.staff_assignment_path(conn, :show, assignment))

      {:error, %Ecto.Changeset{} = changeset} ->
        teamsets = Inkfish.Teams.list_teamsets(conn.assigns[:course])
        render(conn, "new.html", changeset: changeset, teamsets: teamsets)
    end
  end

  def show(conn, %{"id" => id}) do
    assignment = Assignments.get_assignment_for_staff!(id)
    subs = Assignments.list_active_subs(assignment)
    render(conn, "show.html", assignment: %{assignment | subs: subs})
  end

  def edit(conn, %{"id" => id}) do
    assignment = Assignments.get_assignment!(id)
    changeset = Assignments.change_assignment(assignment)
    teamsets = Inkfish.Teams.list_teamsets(conn.assigns[:course])
    render(conn, "edit.html", assignment: assignment,
      changeset: changeset, teamsets: teamsets)
  end

  def update(conn, %{"id" => id, "assignment" => assignment_params}) do
    assignment = Assignments.get_assignment!(id)

    case Assignments.update_assignment(assignment, assignment_params) do
      {:ok, assignment} ->
        conn
        |> put_flash(:info, "Assignment updated successfully.")
        |> redirect(to: Routes.staff_assignment_path(conn, :show, assignment))

      {:error, %Ecto.Changeset{} = changeset} ->
        teamsets = Inkfish.Teams.list_teamsets(conn.assigns[:course])
        render(conn, "edit.html", assignment: assignment, changeset: changeset,
          teamsets: teamsets)
    end
  end

  def delete(conn, %{"id" => id}) do
    assignment = Assignments.get_assignment!(id)
    {:ok, _assignment} = Assignments.delete_assignment(assignment)

    conn
    |> put_flash(:info, "Assignment deleted successfully.")
    |> redirect(to: Routes.staff_assignment_path(conn, :index))
  end
end

apps/inkfish_web/lib/inkfish_web/controllers/staff/bucket_controller.ex
defmodule InkfishWeb.Staff.BucketController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs
  plug Plugs.FetchItem, [course: "course_id"]
    when action in [:index, :new, :create]
  plug Plugs.FetchItem, [bucket: "id"]
    when action not in [:index, :new, :create]

  plug Plugs.RequireReg, staff: true

  alias InkfishWeb.Plugs.Breadcrumb
  plug Breadcrumb, {"Courses (Staff)", :staff_course, :index}
  plug Breadcrumb, {:show, :staff, :course}
  plug Breadcrumb, {"Buckets", :staff_course_bucket, :index, :course}
    when action not in [:index, :new, :create]

  alias Inkfish.Courses
  alias Inkfish.Courses.Bucket

  def index(conn, %{"course_id" => course_id}) do
    conn = assign(conn, :page_title, "List Buckets")
    buckets = Courses.list_buckets(course_id)
    render(conn, "index.html", buckets: buckets)
  end

  def new(conn, %{"course_id" => course_id}) do
    defaults = %Bucket{
      course_id: course_id,
      weight: 100,
    }
    changeset = Courses.change_bucket(defaults)
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"course_id" => course_id, "bucket" => bucket_params}) do
    bucket_params = Map.put(bucket_params, "course_id", course_id)

    case Courses.create_bucket(bucket_params) do
      {:ok, bucket} ->
        conn
        |> put_flash(:info, "Bucket created successfully.")
        |> redirect(to: Routes.staff_bucket_path(conn, :show, bucket))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    bucket = Courses.get_bucket!(id)
    render(conn, "show.html", bucket: bucket)
  end

  def edit(conn, %{"id" => id}) do
    bucket = Courses.get_bucket!(id)
    changeset = Courses.change_bucket(bucket)
    render(conn, "edit.html", bucket: bucket, changeset: changeset)
  end

  def update(conn, %{"id" => id, "bucket" => bucket_params}) do
    bucket = Courses.get_bucket!(id)

    case Courses.update_bucket(bucket, bucket_params) do
      {:ok, bucket} ->
        conn
        |> put_flash(:info, "Bucket updated successfully.")
        |> redirect(to: Routes.staff_bucket_path(conn, :show, bucket))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", bucket: bucket, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    bucket = Courses.get_bucket!(id)
    {:ok, _bucket} = Courses.delete_bucket(bucket)

    conn
    |> put_flash(:info, "Bucket deleted successfully.")
    |> redirect(to: Routes.staff_bucket_path(conn, :index))
  end
end

apps/inkfish_web/lib/inkfish_web/controllers/staff/course_controller.ex
defmodule InkfishWeb.Staff.CourseController do
  use InkfishWeb, :controller

  plug InkfishWeb.Plugs.FetchItem, [course: "id"]
    when action not in [:index, :new, :create]

  plug InkfishWeb.Plugs.Breadcrumb, {"Courses (Staff)", :staff_course, :index}
  plug InkfishWeb.Plugs.Breadcrumb, {:show, :staff, :course}
    when action not in [:index, :new, :create]

  alias Inkfish.Courses
  alias Inkfish.Courses.Course
  alias Inkfish.Teams

  def index(conn, _params) do
    courses = Courses.list_courses()
    render(conn, "index.html", courses: courses)
  end

  def new(conn, _params) do
    changeset = Courses.change_course(%Course{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"course" => course_params}) do
    case Courses.create_course(course_params) do
      {:ok, course} ->
        conn
        |> put_flash(:info, "Course created successfully.")
        |> redirect(to: Routes.staff_course_path(conn, :show, course))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    course = Courses.get_course_for_staff_view!(id)
    render(conn, "show.html", course: course)
  end

  def edit(conn, %{"id" => id}) do
    course = conn.assigns[:course]
    changeset = Courses.change_course(course)
    render(conn, "edit.html", course: course, changeset: changeset)
  end

  def update(conn, %{"id" => id, "course" => course_params}) do
    course = conn.assigns[:course]

    case Courses.update_course(course, course_params) do
      {:ok, course} ->
        conn
        |> put_flash(:info, "Course updated successfully.")
        |> redirect(to: Routes.staff_course_path(conn, :show, course))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", course: course, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    course = conn.assigns[:course]
    {:ok, _course} = Courses.delete_course(course)

    conn
    |> put_flash(:info, "Course deleted successfully.")
    |> redirect(to: Routes.staff_course_path(conn, :index))
  end
end

apps/inkfish_web/lib/inkfish_web/controllers/staff/grade_column_controller.ex
defmodule InkfishWeb.Staff.GradeColumnController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs
  plug Plugs.FetchItem, [assignment: "assignment_id"]
    when action in [:index, :new, :create]
  plug Plugs.FetchItem, [grade_column: "id"]
    when action not in [:index, :new, :create]

  plug Plugs.RequireReg, staff: true

  alias Plugs.Breadcrumb
  plug Breadcrumb, {"Courses (Staff)", :staff_course, :index}
  plug Breadcrumb, {:show, :staff, :course}
  plug Breadcrumb, {:show, :staff, :assignment}

  alias Inkfish.Grades
  alias Inkfish.Grades.GradeColumn

  def index(conn, _params) do
    grade_columns = Grades.list_grade_columns()
    render(conn, "index.html", grade_columns: grade_columns)
  end

  def new(conn, _params) do
    defaults = %GradeColumn{
      points: Decimal.new("50"),
      base: Decimal.new("25"),
    }
    changeset = Grades.change_grade_column(defaults)
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"grade_column" => grade_column_params}) do
    grade_column_params = Map.put(
      grade_column_params, "assignment_id", conn.assigns[:assignment].id)

    case Grades.create_grade_column(grade_column_params) do
      {:ok, grade_column} ->
        conn
        |> put_flash(:info, "Grade_Column created successfully.")
        |> redirect(to: Routes.staff_grade_column_path(conn, :show, grade_column))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    grade_column = Grades.get_grade_column!(id)
    render(conn, "show.html", grade_column: grade_column)
  end

  def edit(conn, %{"id" => id}) do
    grade_column = Grades.get_grade_column!(id)
    changeset = Grades.change_grade_column(grade_column)
    render(conn, "edit.html", grade_column: grade_column, changeset: changeset)
  end

  def update(conn, %{"id" => id, "grade_column" => grade_column_params}) do
    grade_column = Grades.get_grade_column!(id)

    case Grades.update_grade_column(grade_column, grade_column_params) do
      {:ok, grade_column} ->
        conn
        |> put_flash(:info, "Grade_Column updated successfully.")
        |> redirect(to: Routes.staff_grade_column_path(conn, :show, grade_column))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", grade_column: grade_column, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    grade_column = Grades.get_grade_column!(id)
    {:ok, _grade_column} = Grades.delete_grade_column(grade_column)

    conn
    |> put_flash(:info, "Grade column deleted successfully.")
    |> redirect(to: Routes.staff_grade_column_path(conn, :index))
  end
end

apps/inkfish_web/lib/inkfish_web/views/reg_view.ex
defmodule InkfishWeb.RegView do
  use InkfishWeb, :view

  def render("reg.json", %{reg: reg}) do
    user = get_assoc(reg, :user)

    %{
      user: render_one(user, InkfishWeb.UserView, "user.json"),
    }
  end
end

apps/inkfish_web/lib/inkfish_web/views/staff/bucket_view.ex
defmodule InkfishWeb.Staff.BucketView do
  use InkfishWeb, :view
end

apps/inkfish_web/lib/inkfish_web/views/staff/grade_column_view.ex
defmodule InkfishWeb.Staff.GradeColumnView do
  use InkfishWeb, :view
end

apps/inkfish_web/lib/inkfish_web/templates/staff/reg/edit.html.eex
<h1>Edit Reg</h1>

<%= form_for @changeset, Routes.staff_reg_path(@conn, :update, @reg), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <p>Course: <%= @course.name %></p>
  </div>

  <div class="form-group">
    <p>User: <%= user_display_name(@reg.user) %></p>
  </div>

  <div class="form-group">
    <%= label f, :is_grade_column %>
    <%= checkbox f, :is_grade_column, class: "form-control toggle" %>
    <%= error_tag f, :is_grade_column %>
  </div>

  <div class="form-group">
    <%= label f, :is_prof %>
    <%= checkbox f, :is_prof, class: "form-control toggle" %>
    <%= error_tag f, :is_prof %>
  </div>

  <div class="form-group">
    <%= label f, :is_staff %>
    <%= checkbox f, :is_staff, class: "form-control toggle" %>
    <%= error_tag f, :is_staff %>
  </div>

  <div class="form-group">
    <%= label f, :is_student %>
    <%= checkbox f, :is_student, class: "form-control toggle" %>
    <%= error_tag f, :is_student %>
  </div>

  <div>
    <%= submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

apps/inkfish_web/lib/inkfish_web/templates/staff/reg/index.html.eex
<h1>Listing Regs</h1>

<p>
  <%= link "New Reg", to: Routes.staff_course_reg_path(@conn, :new, @course) %>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Is grader</th>
      <th>Is prof</th>
      <th>Is staff</th>
      <th>Is student</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for reg <- @regs do %>
  <tr>
    <td><%= link(user_display_name(reg.user),
        to: Routes.staff_reg_path(@conn, :show, reg)) %></td>
    <td><%= reg.is_grader %></td>
    <td><%= reg.is_prof %></td>
    <td><%= reg.is_staff %></td>
    <td><%= reg.is_student %></td>

    <td>
      <%= link "Edit", to: Routes.staff_reg_path(@conn, :edit, reg) %>
      <%= link "Delete", to: Routes.staff_reg_path(@conn, :delete, reg), method: :delete, data: [confirm: "Are you sure?"] %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>

apps/inkfish_web/lib/inkfish_web/templates/staff/reg/new.html.eex
<h1>New Reg</h1>

<%= form_for @changeset, Routes.staff_course_reg_path(@conn, :create, @course), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <p>Course: <%= @course.name %></p>
  </div>

  <div class="form-group">
    <%= label f, :user_login %>
    <%= text_input(f, :user_login, class: "form-control autosearch",
                   data: [topic: "users"]) %>
    <%= error_tag f, :user_login %>
    <div class="text-muted">
      Username; start typing to search
    </div>
  </div>

  <div class="form-group">
    <%= label f, :is_grade_column %>
    <%= checkbox f, :is_grade_column, class: "form-control toggle" %>
    <%= error_tag f, :is_grade_column %>
  </div>

  <div class="form-group">
    <%= label f, :is_prof %>
    <%= checkbox f, :is_prof, class: "form-control toggle" %>
    <%= error_tag f, :is_prof %>
  </div>

  <div class="form-group">
    <%= label f, :is_staff %>
    <%= checkbox f, :is_staff, class: "form-control toggle" %>
    <%= error_tag f, :is_staff %>
  </div>

  <div class="form-group">
    <%= label f, :is_student %>
    <%= checkbox f, :is_student, class: "form-control toggle" %>
    <%= error_tag f, :is_student %>
  </div>

  <div>
    <%= submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

apps/inkfish_web/lib/inkfish_web/templates/staff/reg/show.html.eex
<h1>Show Reg</h1>

<p>
  <%= link "Edit", to: Routes.staff_reg_path(@conn, :edit, @reg) %>
</p>

<ul>
  <li>
    <strong>Name:</strong>
    <%= user_display_name(@reg.user) %>

  <li>
    <strong>Is grader:</strong>
    <%= @reg.is_grader %>
  </li>

  <li>
    <strong>Is prof:</strong>
    <%= @reg.is_prof %>
  </li>

  <li>
    <strong>Is staff:</strong>
    <%= @reg.is_staff %>
  </li>

  <li>
    <strong>Is student:</strong>
    <%= @reg.is_student %>
  </li>
</ul>

<h2>Submissions</h2>

<%= Enum.map @course.buckets, fn bucket -> %>
  <h3><%= bucket.name %></h3>

  <table class="table table-striped">
    <thead>
      <th>Active?</th>
      <th>Timestamp</th>
      <th>Score</th>
      <th>Actions</th>
    </thead>
    <tbody>
      <%= Enum.map bucket.assignments, fn as -> %>
        <tr class="table-secondary">
          <td>&nbsp;</td>
          <td colspan="3"><strong><%= as.name %></strong></td>
        </tr>

        <%= Enum.map (@subs[as.id] || []), fn sub -> %>
          <tr>
            <td><%= if sub.active, do: "✓" %></td>
            <td><%= link(sub.inserted_at,
                to: Routes.staff_sub_path(@conn, :show, sub)) %></td>
            <td><%= sub.score || "∅" %> / <%= assignment_total_points(as) %></td>
            <td>
              <%= unless sub.active do %>
                <% path = Routes.staff_sub_path(@conn, :update, sub) %>
                <% cset = Inkfish.Subs.change_sub(%{sub | active: true}) %>
                <%= form_for cset, path, fn f -> %>
                  <%= hidden_input f, :active %>
                  <%= submit "Set Active", class: "btn btn-secondary" %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>