apps/inkfish_web/lib/inkfish_web/router.ex
defmodule InkfishWeb.Router do
  use InkfishWeb, :router
  
  alias InkfishWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug Plugs.Assign, client_mode: :browser
    plug :fetch_session
    plug Plugs.FetchUser
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.Breadcrumb, {"Home", :page, :index}
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug Plugs.Assign, client_mode: :ajax
    plug :fetch_session
    plug Plugs.FetchUser
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end
  
  pipeline :admin do
    plug Plugs.RequireUser, is_admin: true
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", InkfishWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/dashboard", PageController, :dashboard
    resources "/session", SessionController, only: [:create, :delete], singleton: true
    resources "/users", UserController, only: [:show, :edit, :update]
    resources "/uploads", UploadController, only: [:create, :show]
    get "/uploads/:id/thumb", UploadController, :thumb
    resources "/courses", CourseController, only: [:index, :show] do
      resources "/regs", RegController, only: [:index, :new, :create]
      resources "/join_reqs", JoinReqController, only: [:new, :create]
      resources "/teams", TeamController, only: [:index, :new, :create]
    end
    resources "/regs", RegController, except: [:index, :new, :create]
    resources "/teams", TeamController, except: [:index, :new, :create]
    resources "/assignments", AssignmentController, only: [:show] do
      resources "/subs", SubController, only: [:new, :create]
    end
    resources "/subs", SubController, only: [:show]
    resources "/grade_columns", GradeColumnController, only: [:show]
    resources "/grades", GradeController, only: [:show]
  end

  scope "/staff", InkfishWeb.Staff, as: :staff do
    pipe_through :browser

    resources "/courses", CourseController do
      resources "/regs", RegController, only: [:index, :new, :create]
      resources "/join_reqs", JoinReqController, only: [:index]
      resources "/teamsets", TeamsetController, only: [:index, :new, :create]
      resources "/buckets", BucketController, only: [:index, :new, :create]
    end
    resources "/regs", RegController, except: [:index, :new, :create]
    resources "/join_reqs", JoinReqController, only: [:show, :delete]
    post "/join_reqs/:id/accept", JoinReqController, :accept
    resources "/teamsets", TeamsetController, except: [:index, :new, :create]
    resources "/buckets", BucketController, except: [:index, :new, :create] do
      resources "/assignments", AssignmentController, only: [:index, :new, :create]
    end
    resources "/assignments", AssignmentController, except: [:index, :new, :create] do
      resources "/grade_columns", GradeColumnController, only: [:index, :new, :create]
    end
    resources "/grade_columns", GradeColumnController, except: [:index, :new, :create]
    resources "/subs", SubController, only: [:show, :update] do
      resources "/grades", GradeController, only: [:create]
    end
    resources "/grades", GradeController, only: [:edit, :show]
  end

  scope "/admin", InkfishWeb.Admin, as: :admin do
    pipe_through [:browser, :admin]
    
    resources "/users", UserController
    resources "/courses", CourseController
    resources "/uploads", UploadController
  end

  scope "/ajax", InkfishWeb, as: :ajax do
    pipe_through :ajax

    post "/uploads", UploadController, :create
  end

  scope "/ajax/staff", InkfishWeb.Staff, as: :ajax_staff do
    pipe_through :ajax

    resources "/subs", SubController, only: [] do
      resources "/grades", GradeController, only: [:create]
    end
    resources "/grades", GradeController, only: [] do
      resources "/line_comments", LineCommentController, only: [:create]
    end
    resources "/line_comments", LineCommentController, except: [:new, :edit, :create]
    resources "/teamsets", TeamsetController, only: [] do
      resources "/teams", TeamController, only: [:index, :create]
    end
    resources "/teams", TeamController, only: [:show, :update, :delete]
  end
end

apps/inkfish_web/lib/inkfish_web/views/layout_view.ex
defmodule InkfishWeb.LayoutView do
  use InkfishWeb, :view
  
  def page_title(conn) do
    if conn.assigns[:page_title] do
      conn.assigns[:page_title]
    else
      sec = String.capitalize(current_controller(conn))
      act = String.capitalize(current_action(conn))
      if act == "Index" do
        Inflex.pluralize("List #{sec}")
      else
        "#{act} #{sec}"
      end
    end
  end
  
  def current_controller(conn) do
    mod = to_string(conn.private.phoenix_controller)
    [_, sec] = Regex.run(~r{InkfishWeb\.(?:\w+\.)?(\w+)Controller$}, mod)
    sec
  end

  def current_controller_full(conn) do
    mod = to_string(conn.private.phoenix_controller)
    [_, sec] = Regex.run(~r{InkfishWeb\.([\w\.]+)Controller$}, mod)
    sec
  end
  
  def current_action(conn) do
    to_string(conn.private.phoenix_action)
  end
  
  def current_page(conn) do
    sec = String.downcase(current_controller_full(conn))
    act = String.downcase(current_action(conn))
    "#{sec}/#{act}"
  end

  ## Breadcrumbs
  def item_type_name(item) do
    struct_name = to_string(item.__struct__)
    String.downcase(String.replace(struct_name, ~r(^.*\.), ""))
  end

  def crumb_to_link(conn, {:show, key}) do
    crumb_to_link(conn, {:show, nil, key})
  end

  def crumb_to_link(_conn, {name, path}) do
    crumb = safe_to_string(link name, to: path)
    ~s[<li class="breadcrumb-item">#{crumb}</li>]
  end

  def crumb_to_link(conn, {:show, prefix, key}) do
    item = conn.assigns[key]
    type = item_type_name(item)
    parts = Enum.filter [prefix, type, "path"], &(&1 != nil)
    func = String.to_atom(Enum.join(parts, "_"))
    path = apply(Routes, func, [conn, :show, item])
    if Map.get(item, :name) do
      crumb_to_link(conn, {item.name, path})
    else
      type_name = String.capitalize(type)
      crumb_to_link(conn, {"#{type_name} ##{item.id}", path})
    end
  end
 
  def crumb_to_link(conn, {name, helper, action}) do
    func = String.to_atom(Atom.to_string(helper) <> "_path")
    path = apply(Routes, func, [conn, action])
    crumb_to_link(conn, {name, path})
  end

  def crumb_to_link(conn, {name, helper, action, key}) do
    func = String.to_atom(Atom.to_string(helper) <> "_path")
    path = apply(Routes, func, [conn, action, conn.assigns[key]])
    crumb_to_link(conn, {name, path})
  end

  def breadcrumb(conn) do
    crumbs = Enum.reverse(conn.assigns[:breadcrumb] || [])
    items = Enum.map crumbs, &(crumb_to_link(conn, &1))
    title = page_title(conn)
   
    html = ~s[
        <ul class="breadcrumb">
          #{items}
          <li class="breadcrumb-item active">#{title}</li>
        </ul>
    ]
    raw(html)
  end
end

apps/inkfish_web/lib/inkfish_web/templates/layout/admin_nav.html.eex
Admin:
<%= link "Users", to: Routes.admin_user_path(@conn, :index) %> |
<%= link "Courses", to: Routes.admin_course_path(@conn, :index) %>

apps/inkfish_web/lib/inkfish_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= page_title(@conn) %> · Inkfish</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="icon" type="image/png"
          href="<%= Routes.static_path(@conn,"/images/inkfish.png") %>"/>
    <script>
     window.user_token = "<%= @current_user_token %>";
     window.current_page = "<%= current_page(@conn) %>";
     window.csrf_token = "<%= Phoenix.Controller.get_csrf_token() %>";
     window.upload_path = "<%= Routes.ajax_upload_path(@conn, :create) %>";
    </script>
  </head>
  <body>
    <div class="container">
      <header>
        <div class="row">
          <div class="col-md-2">
            <%= link(img_tag(Routes.static_path(@conn, "/images/inkfish.png"),
                  class: "header-logo"), to: Routes.page_path(@conn, :index)) %>
          </div>
          <div class="col-md-5">
            <%= if @current_user && @current_user.is_admin do %>
              <%= render InkfishWeb.LayoutView, "admin_nav.html", assigns %>
            <% else %>
              &nbsp;
            <% end %>
          </div>
          <div class="col-md-5">
            <%= if @current_user do %>
              User: <%= @current_user.email %> |
              <%= link("Profile", to: Routes.user_path(@conn, :show, @current_user)) %> |
              <%= link("Logout", to: Routes.session_path(@conn, :delete),
                       method: :delete) %>
            <% else %>
              <p>no session</p>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= breadcrumb(@conn) %>
          </div>
        </div>
      </header>

      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
      <main>
        <%= render @view_module, @view_template, assigns %>

        <%= if assigns[:course] do %>
          <%= render InkfishWeb.LayoutView, "course_footer.html", assigns %>
        <% end %>
      </main>

      <div class="inkfish-footer">
        <p>Inkfish copyright &copy; 2018-2019 Nat Tuck. Licensed under the GNU AGPLv3. No
          warranty, this code will probably eat your dog. Source code at
          <a href=https://github.com/NatTuck/inkfish">http://github.com/NatTuck/inkfish</a>.
        </p>
      </div>
    </div>
    <script type="text/javascript"
            src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/inkfish_web/lib/inkfish_web/templates/layout/course_footer.html.eex
<div class="row p-2">
  <%= trusted_markdown @course.footer %>
</div>