apps/inkfish_web/lib/inkfish_web/router.ex
defmodule InkfishWeb.Router do
  use InkfishWeb, :router
  
  alias InkfishWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug Plugs.Assign, client_mode: :browser
    plug :fetch_session
    plug Plugs.FetchUser
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.Breadcrumb, {"Home", :page, :index}
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug Plugs.Assign, client_mode: :ajax
    plug :fetch_session
    plug Plugs.FetchUser
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end
  
  pipeline :admin do
    plug Plugs.RequireUser, is_admin: true
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", InkfishWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/dashboard", PageController, :dashboard
    resources "/session", SessionController, only: [:create, :delete], singleton: true
    resources "/users", UserController, only: [:show, :edit, :update]
    resources "/uploads", UploadController, only: [:create, :show]
    get "/uploads/:id/thumb", UploadController, :thumb
    resources "/courses", CourseController, only: [:index, :show] do
      resources "/regs", RegController, only: [:index, :new, :create]
      resources "/join_reqs", JoinReqController, only: [:new, :create]
      resources "/teams", TeamController, only: [:index, :new, :create]
    end
    resources "/regs", RegController, except: [:index, :new, :create]
    resources "/teams", TeamController, except: [:index, :new, :create]
    resources "/assignments", AssignmentController, only: [:show] do
      resources "/subs", SubController, only: [:new, :create]
    end
    resources "/subs", SubController, only: [:show]
    resources "/grade_columns", GradeColumnController, only: [:show]
    resources "/grades", GradeController, only: [:show]
  end

  scope "/staff", InkfishWeb.Staff, as: :staff do
    pipe_through :browser

    resources "/courses", CourseController do
      resources "/regs", RegController, only: [:index, :new, :create]
      resources "/join_reqs", JoinReqController, only: [:index]
      resources "/teamsets", TeamsetController, only: [:index, :new, :create]
      resources "/buckets", BucketController, only: [:index, :new, :create]
    end
    resources "/regs", RegController, except: [:index, :new, :create]
    resources "/join_reqs", JoinReqController, only: [:show, :delete]
    post "/join_reqs/:id/accept", JoinReqController, :accept
    resources "/teamsets", TeamsetController, except: [:index, :new, :create]
    resources "/buckets", BucketController, except: [:index, :new, :create] do
      resources "/assignments", AssignmentController, only: [:index, :new, :create]
    end
    resources "/assignments", AssignmentController, except: [:index, :new, :create] do
      resources "/grade_columns", GradeColumnController, only: [:index, :new, :create]
    end
    resources "/grade_columns", GradeColumnController, except: [:index, :new, :create]
    resources "/subs", SubController, only: [:show, :update] do
      resources "/grades", GradeController, only: [:create]
    end
    resources "/grades", GradeController, only: [:edit, :show]
  end

  scope "/admin", InkfishWeb.Admin, as: :admin do
    pipe_through [:browser, :admin]
    
    resources "/users", UserController
    resources "/courses", CourseController
    resources "/uploads", UploadController
  end

  scope "/ajax", InkfishWeb, as: :ajax do
    pipe_through :ajax

    post "/uploads", UploadController, :create
  end

  scope "/ajax/staff", InkfishWeb.Staff, as: :ajax_staff do
    pipe_through :ajax

    resources "/subs", SubController, only: [] do
      resources "/grades", GradeController, only: [:create]
    end
    resources "/grades", GradeController, only: [] do
      resources "/line_comments", LineCommentController, only: [:create]
    end
    resources "/line_comments", LineCommentController, except: [:new, :edit, :create]
    resources "/teamsets", TeamsetController, only: [] do
      resources "/teams", TeamController, only: [:index, :create]
    end
    resources "/teams", TeamController, only: [:show, :update, :delete]
  end
end

apps/inkfish_web/lib/inkfish_web/controllers/staff/sub_controller.ex
defmodule InkfishWeb.Staff.SubController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs
  plug Plugs.FetchItem, [sub: "id"]
    when action not in [:index, :new, :create]
  plug Plugs.FetchItem, [assignment: "assignment_id"]
    when action in [:index, :new, :create]
  plug Plugs.RequireReg, staff: true

  alias InkfishWeb.Plugs.Breadcrumb
  plug Breadcrumb, {"Courses (Staff)", :staff_course, :index}
  plug Breadcrumb, {:show, :staff, :course}
  plug Breadcrumb, {:show, :staff, :assignment}

  alias Inkfish.Subs
  alias Inkfish.Subs.Sub
  alias Inkfish.Teams

  def show(conn, %{"id" => id}) do
    sub = Subs.get_sub!(id)
    sub = %{sub | team: Teams.get_team!(sub.team_id)}
    render(conn, "show.html", sub: sub)
  end

  def update(conn, %{"id" => id, "sub" => params}) do
    # This can only set a sub active.
    sub = conn.assigns[:sub]

    if params["active"] do
      Subs.set_sub_active!(sub)
    end

    conn
    |> put_flash(:info, "Set sub active: ##{sub.id}.")
    |> redirect(to: Routes.staff_reg_path(conn, :show, sub.reg_id))
  end
end

apps/inkfish_web/lib/inkfish_web/controllers/sub_controller.ex
defmodule InkfishWeb.SubController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs
  plug Plugs.FetchItem, [sub: "id"]
    when action not in [:index, :new, :create]
  plug Plugs.FetchItem, [assignment: "assignment_id"]
    when action in [:index, :new, :create]
  plug Plugs.RequireReg
  plug Plugs.RequireSubmitter
    when action in [:show]

  alias InkfishWeb.Plugs.Breadcrumb
  plug Breadcrumb, {:show, :course}
  plug Breadcrumb, {:show, :assignment}

  alias Inkfish.Subs
  alias Inkfish.Subs.Sub
  alias Inkfish.Teams

  def new(conn, _params) do
    asg = conn.assigns[:assignment]
    reg = conn.assigns[:current_reg]
    team = Teams.get_active_team(asg, reg)

    if team do
      changeset = Subs.change_sub(%Sub{})
      render(conn, "new.html", changeset: changeset, team: team)
    else
      conn
      |> put_flash(:error, "You need a team to submit.")
      |> redirect(to: Routes.assignment_path(conn, :show, asg))
    end
  end

  def create(conn, %{"sub" => sub_params}) do
    asg = conn.assigns[:assignment]
    reg = conn.assigns[:current_reg]
    team = Teams.get_active_team(asg, reg)
   
    sub_params = sub_params
    |> Map.put("assignment_id", asg.id)
    |> Map.put("reg_id", reg.id)
    |> Map.put("team_id", team.id)

    case Subs.create_sub(sub_params) do
      {:ok, sub} ->
        conn
        |> put_flash(:info, "Sub created successfully.")
        |> redirect(to: Routes.sub_path(conn, :show, sub))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    sub = Subs.get_sub!(id)
    sub = %{sub | team: Teams.get_team!(sub.team_id)}
    render(conn, "show.html", sub: sub)
  end
end

apps/inkfish_web/lib/inkfish_web/views/staff/sub_view.ex
defmodule InkfishWeb.Staff.SubView do
  use InkfishWeb, :view

  alias Inkfish.Grades.GradeColumn
  alias Inkfish.Grades.Grade

  # FIXME: Does any of this make sense?
  def staff_grade_action(conn, %GradeColumn{} = _gcol, nil) do
    "create"
  end

  def staff_grade_action(conn, %GradeColumn{} = _gcol, %Grade{} = _grade) do
    "edit"
  end

  def render("sub.json", %{sub: sub}) do
    reg = get_assoc(sub, :reg)
    team = get_assoc(sub, :team)

    %{
      active: sub.active,
      assignment_id: sub.assignment_id,
      inserted_at: sub.inserted_at,
      reg_id: sub.reg_id,
      reg: render_one(reg, InkfishWeb.Staff.RegView, "reg.json"),
      team_id: sub.team_id,
      team: render_one(team, InkfishWeb.Staff.TeamView, "team.json"),
    }
  end
end

apps/inkfish_web/lib/inkfish_web/views/sub_view.ex
defmodule InkfishWeb.SubView do
  use InkfishWeb, :view
end

apps/inkfish_web/lib/inkfish_web/templates/sub/new.html.eex
<h1>New Submission</h1>

<p>Course: <%= @course.name %></p>
<p>Assignment: <%= @assignment.name %></p>
<p>Submitting for: <%= show_team(@team) %></p>

<%= form_for @changeset, Routes.assignment_sub_path(@conn, :create, @assignment), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :hours_spent %>
    <%= number_input f, :hours_spent, class: "form-control" %>
    <%= error_tag f, :hours_spent %>
  </div>

  <div class="form-group">
    <%= label f, :note %>
    <%= textarea f, :note, class: "form-control" %>
    <%= error_tag f, :note %>
  </div>

  <div class="form-group sub-upload-group">
    <%= label f, :upload_id %>
    <%= text_input f, :upload_id, class: "form-control", readonly: "readonly" %>
    <%= error_tag f, :upload_id %>

    <% use_tabs = @assignment.allow_upload && @assignment.allow_git %>
    <%= if use_tabs do %>
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link active" id="upload-tab"
             data-toggle="tab" href="#upload-pane">
            Upload File
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="git-tab"
             data-toggle="tab" href="#git-pane">
            Clone Git Repo
          </a>
        </li>
      </ul>
    <% else %>
      <script>
       $(() => $('#git-pane').show());
      </script>
    <% end %>

    <div class="tab-content" id="upload-panes">

      <%= if @assignment.allow_upload do %>
        <div class="tab-pane fade show active" id="upload-pane">
          <%= ajax_upload_field "sub", "tgz,gz,txt", "sub_upload_id" %>
        </div>
      <% end %>

      <%= if @assignment.allow_git do %>
        <div class="tab-pane fade <%= if !use_tabs, do: "show active" %>" id="git-pane">
          <div class="row my-2">
            <div class="col-md-8 form-group">
              <input type="text" placeholder="https://github.com/YourName/repo.git"
                     class="form-control" id="git-clone-input">
            </div>
            <div class="col-md-4 form-group">
              <button class="btn btn-secondary" id="git-clone-btn">Git Clone</button>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="output-log" id="git-output-log"
                   data-id-field="sub_upload_id"></div>
            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>

  <div>
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

apps/inkfish_web/lib/inkfish_web/templates/sub/show.html.eex
<h1>Show Sub</h1>

<ul>
  <li>
    <strong>Team:</strong>
    <%= show_team(@sub.team) %>
  </li>

  <li>
    <strong>Submitter:</strong>
    <%= user_display_name(@sub.reg.user) %>
  </li>

  <li>
    <strong>Timestamp:</strong>
    <%= @sub.inserted_at %>
  </li>

  <li>
    <strong>Active:</strong>
    <%= @sub.active %>
  </li>

  <li>
    <strong>Hours Spent:</strong>
    <%= @sub.hours_spent %>
  </li>

  <li>
    <strong>Upload:</strong>
    <%= link @sub.upload.name, to: Routes.upload_path(@conn, :show, @sub.upload) %>
  </li>
</ul>

<p><strong>Student Note:</strong></p>

<p><%= sanitize_markdown(@sub.note) %></p>

<h2>Grades</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Score</th>
    </tr>
  </thead>
  <%= for grade_column <- @assignment.grade_columns do %>
    <% grade = Enum.find(@sub.grades, &(&1.grade_column_id == grade_column.id)) %>
    <tr>
      <td>
        <%= if grade && !grade_hidden?(@conn, @assignment) do %>
          <%= if grade_column.kind == "feedback" do %>
            <%= link grade_column.name, to: Routes.grade_path(@conn, :show, grade.id) %>
          <% else %>
            <%= grade_column.name %>
          <% end %>
        <% else %>
          <%= grade_column.name %>
        <% end %>
      </td>
      <td><%= show_score(@conn, grade) %> / <%= grade_column.points %></td>
    </tr>
  <% end %>
  <tr>
    <td>Late Penalty</td>
    <td><%= show_score(@sub.late_penalty) %></td>
  </tr>
  <tr>
    <td>Total Score</td>
    <td><%= show_score(@conn, @sub) %> / <%= assignment_total_points(@assignment) %></td>
  </tr>
</table>